# Sprint 5 Runner (Colab)

<!-- Cell 0: Judul notebook - intro Sprint 5 Plan v3 -->

Notebook khusus untuk menjalankan `Sprint 5 Plan v3` end-to-end dengan output log tampil penuh di setiap sel.

## 0) Settings

<!-- Cell 1: Header section Settings -->

Isi `REPO_URL` dengan repository kamu. Kalau repo private, pastikan token/Git auth sudah siap di Colab.

In [1]:
# Cell 2: Core settings - REPO_URL, branch, path, stage toggles
REPO_URL = 'https://github.com/akwancakra/nids-cnn-lstm-autoencoder.git'  # contoh: https://github.com/<user>/<repo>.git
REPO_BRANCH = 'feat/sprint5-cse-fpr-reduction'  # branch yang mau dipakai di Colab
PROJECT_NAME = 'nids-cnn-lstm-autoencoder'
DRIVE_ROOT = '/content/drive/MyDrive/nids-cnn-lstm-autoencoder'

# Raw dataset source (default mengikuti Sprint 3)
# Jika folder ini tidak ada, notebook fallback ke {DRIVE_ROOT}/data/raw
RAW_DRIVE_SOURCE = '/content/drive/MyDrive/nids-data/raw'

FORCE_RECLONE = False

# Stage toggles (set True/False sesuai kebutuhan)
RUN_STAGE0 = True
RUN_STAGE1 = True
RUN_STAGE2 = False
RUN_STAGE3_4 = True
RUN_SUMMARIZE = True

In [2]:
# Cell 3: Colab bootstrap + mount Google Drive
import os
import sys
import json
import time
import shlex
import shutil
import subprocess
from pathlib import Path

IN_COLAB = 'google.colab' in sys.modules
print('IN_COLAB =', IN_COLAB)

if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')

Path(DRIVE_ROOT).mkdir(parents=True, exist_ok=True)
print('DRIVE_ROOT =', DRIVE_ROOT)

IN_COLAB = True
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
DRIVE_ROOT = /content/drive/MyDrive/nids-cnn-lstm-autoencoder

In [3]:
# Cell 4: Clone atau update repo di /content + checkout branch
PROJECT_ROOT = Path('/content') / PROJECT_NAME

if FORCE_RECLONE and PROJECT_ROOT.exists():
    shutil.rmtree(PROJECT_ROOT)

if not PROJECT_ROOT.exists():
    if '<REPO_URL_HERE>' in REPO_URL:
        raise ValueError('Set REPO_URL dulu di cell Settings')
    cmd = ['git', 'clone', REPO_URL, str(PROJECT_ROOT)]
    print('[CMD]', ' '.join(cmd))
    subprocess.run(cmd, check=True)

os.chdir(PROJECT_ROOT)
print('PROJECT_ROOT =', PROJECT_ROOT)
print('cwd =', Path.cwd())

# Always sync and checkout selected branch
subprocess.run(['git', '-C', str(PROJECT_ROOT), 'fetch', '--all', '--prune'], check=False)

# Try checkout branch; if branch only exists on origin, create tracking local branch.
ret = subprocess.run(['git', '-C', str(PROJECT_ROOT), 'checkout', REPO_BRANCH], check=False)
if ret.returncode != 0:
    subprocess.run(['git', '-C', str(PROJECT_ROOT), 'checkout', '-b', REPO_BRANCH, f'origin/{REPO_BRANCH}'], check=True)

# Pull latest on selected branch
subprocess.run(['git', '-C', str(PROJECT_ROOT), 'pull', 'origin', REPO_BRANCH], check=False)

active_branch = subprocess.check_output(['git', '-C', str(PROJECT_ROOT), 'branch', '--show-current'], text=True).strip()
print('[GIT] active branch =', active_branch)

PROJECT_ROOT = /content/nids-cnn-lstm-autoencoder
cwd = /content/nids-cnn-lstm-autoencoder
[GIT] active branch = feat/sprint5-cse-fpr-reduction

In [4]:
# Cell 5: Install dependencies (Colab-safe, skip reinstall numpy/tensorflow)
from pathlib import Path
import importlib.util

req = Path('requirements.txt').resolve()
if not req.exists():
    raise FileNotFoundError(f'requirements.txt not found at {req}')


def _run(cmd):
    print('[CMD]', ' '.join(cmd))
    subprocess.run(cmd, check=True)


if IN_COLAB:
    # IMPORTANT:
    # Colab sudah punya numpy/pandas/scikit/tensorflow yang saling kompatibel.
    # Reinstall paket-paket ini sering memicu ABI mismatch (numpy.dtype size changed).
    print('[INFO] Colab mode: skip reinstall scientific stack (numpy/pandas/scikit-learn/tensorflow).')

    # Install only lightweight utilities if missing.
    lightweight = [
        'pyyaml',
        'joblib',
        'seaborn',
    ]

    for pkg in lightweight:
        mod = 'yaml' if pkg == 'pyyaml' else pkg
        if importlib.util.find_spec(mod) is None:
            _run([sys.executable, '-m', 'pip', 'install', pkg])
        else:
            print(f'[INFO] {pkg} already available')

    print('\n[OK] Dependency step finished (Colab-safe mode).')
    print('[NOTE] Jika sebelumnya sempat install ulang numpy/tensorflow dan masih error, lakukan Factory reset runtime dulu.')
else:
    # Local/non-Colab: follow project requirements as usual.
    _run([sys.executable, '-m', 'pip', 'install', '-r', str(req)])

[INFO] Colab mode: skip reinstall scientific stack (numpy/pandas/scikit-learn/tensorflow).
[INFO] pyyaml already available
[INFO] joblib already available
[INFO] seaborn already available

[OK] Dependency step finished (Colab-safe mode).
[NOTE] Jika sebelumnya sempat install ulang numpy/tensorflow dan masih error, lakukan Factory reset runtime dulu.

In [5]:
# Cell 6: Link data/model/results sprint5 ke Drive (persist setelah disconnect)
os.chdir(PROJECT_ROOT)

raw_source = RAW_DRIVE_SOURCE if Path(RAW_DRIVE_SOURCE).exists() else f'{DRIVE_ROOT}/data/raw'
print(f'[RAW] using source: {raw_source}')

paths = [
    ('data/raw', raw_source),
    ('data/sprint5', f'{DRIVE_ROOT}/data/sprint5'),
    ('models/sprint5', f'{DRIVE_ROOT}/models/sprint5'),
    ('results/sprint5', f'{DRIVE_ROOT}/results/sprint5'),
]

for _, dst in paths:
    Path(dst).mkdir(parents=True, exist_ok=True)

for src, dst in paths:
    src_path = Path(src)
    if src_path.is_symlink() or src_path.exists():
        if src_path.is_symlink() or src_path.is_file():
            src_path.unlink()
        else:
            shutil.rmtree(src_path)
    src_path.parent.mkdir(parents=True, exist_ok=True)
    src_path.symlink_to(Path(dst), target_is_directory=True)
    print(f'[LINK] {src} -> {dst}')

print('[OK] Symlink setup complete')

# Fast preflight check
required_dirs = [
    Path('data/raw/CIC-IDS2017'),
    Path('data/raw/CSE-CIC-IDS2018'),
]
for d in required_dirs:
    print(f'[CHECK] {d}:', 'OK' if d.exists() else 'MISSING')

[RAW] using source: /content/drive/MyDrive/nids-data/raw
[LINK] data/raw -> /content/drive/MyDrive/nids-data/raw
[LINK] data/sprint5 -> /content/drive/MyDrive/nids-cnn-lstm-autoencoder/data/sprint5
[LINK] models/sprint5 -> /content/drive/MyDrive/nids-cnn-lstm-autoencoder/models/sprint5
[LINK] results/sprint5 -> /content/drive/MyDrive/nids-cnn-lstm-autoencoder/results/sprint5
[OK] Symlink setup complete
[CHECK] data/raw/CIC-IDS2017: OK
[CHECK] data/raw/CSE-CIC-IDS2018: OK

In [6]:
# Cell 7: GPU check + run_cmd_stream helper (streaming output ke cell)
try:
    import tensorflow as tf
except Exception as e:
    print('[ERROR] TensorFlow import gagal:', repr(e))
    print('Kemungkinan besar environment ABI belum sinkron setelah pip install.')
    print('Solusi: Runtime > Restart runtime, lalu jalankan lagi dari cell GPU check ini.')
    raise

print('Python executable :', sys.executable)
print('TensorFlow        :', tf.__version__)
print('Built with CUDA   :', tf.test.is_built_with_cuda())
print('Built with GPU sup:', tf.test.is_built_with_gpu_support())
print('Physical GPU list :', tf.config.list_physical_devices('GPU'))
print('Logical GPU list  :', tf.config.list_logical_devices('GPU'))

# Maksimalkan penggunaan GPU: memory growth agar TF pakai memori dinamis
gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    try:
        tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError:
        pass
if gpus:
    print('[GPU] Memory growth enabled -> training/eval akan memaksimalkan GPU.')


def _fmt_duration(seconds: float) -> str:
    sec = max(0, int(seconds))
    h, rem = divmod(sec, 3600)
    m, s = divmod(rem, 60)
    if h > 0:
        return f'{h}h {m:02d}m {s:02d}s'
    if m > 0:
        return f'{m}m {s:02d}s'
    return f'{s}s'


def _normalize_cmd(cmd: str):
    parts = shlex.split(cmd, posix=False)
    if parts and parts[0].lower() == 'python':
        parts[0] = sys.executable
    return parts


def run_cmd_stream(title: str, cmd: str, log_to_file: bool = True):
    """Jalankan command dengan streaming output ke cell. Log lengkap disimpan ke file."""
    print(f'[RUN] {title}', flush=True)
    args = _normalize_cmd(cmd)
    print('[CMD]', ' '.join(args), flush=True)
    t0 = time.time()

    env = dict(os.environ)
    env["PYTHONUNBUFFERED"] = "1"

    proc = subprocess.Popen(
        args,
        cwd=str(PROJECT_ROOT),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        env=env,
    )

    log_path = None
    log_file = None
    if log_to_file:
        log_dir = PROJECT_ROOT / 'results' / 'sprint5' / 'runtime'
        log_dir.mkdir(parents=True, exist_ok=True)
        ts = time.strftime('%Y%m%d_%H%M%S', time.gmtime())
        log_path = log_dir / f'log_{title.replace(" ", "_")}_{ts}.txt'
        log_file = open(log_path, 'w', encoding='utf-8')

    last_line = ''
    try:
        for line in proc.stdout or []:
            print(line, end='', flush=True)
            if log_file:
                log_file.write(line)
                log_file.flush()
            last_line = line.strip()
    finally:
        if log_file:
            log_file.close()
            print(f'\n[LOG] Full log saved to: {log_path}', flush=True)

    ret = proc.wait()
    print(f'\n[EXIT CODE] {ret}', flush=True)
    if ret != 0:
        raise RuntimeError(f"{title} failed (exit={ret}). Last line: {last_line}")

    print(f'[DONE] {title} in {_fmt_duration(time.time() - t0)}', flush=True)


def run_stage(stage_name: str):
    run_cmd_stream(
        title=f'Sprint5 {stage_name}',
        cmd=f'python scripts/sprint5/research_runner.py --stage-names {stage_name} --skip-existing',
    )

Python executable : /usr/bin/python3
TensorFlow        : 2.19.0
Built with CUDA   : True
Built with GPU sup: True
Physical GPU list : [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Logical GPU list  : [LogicalDevice(name='/device:GPU:0', device_type='GPU')]
[GPU] Memory growth enabled -> training/eval akan memaksimalkan GPU.

## 1) Optional Dry-Run

<!-- Cell 8: Header dry-run - validasi tanpa eksekusi real -->

Validasi command tanpa eksekusi real training/eval.

In [7]:
# Cell 9: Execute dry-run stage0 (validasi command tanpa training/eval real)
run_cmd_stream(
    title='Sprint5 Dry-Run Stage0',
    cmd='python scripts/sprint5/research_runner.py --dry-run --stage-names stage0 --no-summarize',
)

[RUN] Sprint5 Dry-Run Stage0
[CMD] /usr/bin/python3 scripts/sprint5/research_runner.py --dry-run --stage-names stage0 --no-summarize
[RUN] s5_00_lock_baseline | stage=stage0 | stages=['preprocess', 'train', 'eval'] | tag=s5_00_lock_baseline
[CMD] /usr/bin/python3 scripts/sprint5/preprocess.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_00_lock_baseline.yaml
[CMD] /usr/bin/python3 scripts/sprint5/train.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_00_lock_baseline.yaml --variant hybrid
[CMD] /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_00_lock_baseline.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_00_lock_baseline
[RUN] s5_m07_rerun | stage=stage0 | stages=['train', 'eval'] | tag=s5_m07_rerun
[CMD] /usr/bin/python3 scripts/sprint5/train.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_m07_rerun.yaml --variant hybrid
[CMD] /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_m07_rerun.yaml --model models/sprint5/s5_m07_rerun/cnn_lstm_ae/best_model.keras --tag s5_m07_rerun

[LOG] Full log saved to: /content/nids-cnn-lstm-autoencoder/results/sprint5/runtime/log_Sprint5_Dry-Run_Stage0_20260301_092533.txt

[EXIT CODE] 0
[DONE] Sprint5 Dry-Run Stage0 in 10s

## 2) Execute Sprint 5 Stages

<!-- Cell 10: Header execute stages -->

In [8]:
# Cell 11: Execute stage0 (repro + strict contract runs)
if RUN_STAGE0:
    run_stage('stage0')
else:
    print('[SKIP] stage0')

[RUN] Sprint5 stage0
[CMD] /usr/bin/python3 scripts/sprint5/research_runner.py --stage-names stage0 --skip-existing
[SKIP] s5_00_lock_baseline metrics already exist for tag=s5_00_lock_baseline
[SKIP] s5_m07_rerun metrics already exist for tag=s5_m07_rerun
[DONE] summary: /content/nids-cnn-lstm-autoencoder/results/sprint5/summary.csv
[DONE] report: /content/nids-cnn-lstm-autoencoder/docs/sprint5/RESEARCH_REPORT_CSE_F1_SPRINT5.md
[DONE] gate: /content/nids-cnn-lstm-autoencoder/results/sprint5/gate_decision.json

[LOG] Full log saved to: /content/nids-cnn-lstm-autoencoder/results/sprint5/runtime/log_Sprint5_stage0_20260301_092544.txt

[EXIT CODE] 0
[DONE] Sprint5 stage0 in 5s

In [9]:
# Cell 12: Execute stage1 (7 target threshold variant runs)
if RUN_STAGE1:
    run_stage('stage1')
else:
    print('[SKIP] stage1')

[RUN] Sprint5 stage1
[CMD] /usr/bin/python3 scripts/sprint5/research_runner.py --stage-names stage1 --skip-existing
[RUN] s5_t01_target_p95 | stage=stage1 | stages=['eval'] | tag=s5_t01_target_p95
[CMD] /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t01_target_p95.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t01_target_p95
2026-03-01 09:25:52.634557: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772357152.656354    8708 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772357152.663640    8708 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772357152.679970    8708 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772357152.680007    8708 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772357152.680010    8708 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772357152.680011    8708 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[STAGE] Using GPU for evaluation (devices=1).
I0000 00:00:1772357159.215465    8708 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13655 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2026-03-01 09:26:03,844 | INFO | [STAGE] Evaluate shard mode | source_split=calib source_shards=18 cic_shards=18 cse_shards=54
I0000 00:00:1772357165.859151    8802 cuda_dnn.cc:529] Loaded cuDNN version 91002
2026-03-01 09:26:07,583 | INFO | [PROGRESS] Collecting scores | shards:1/18 (5.6%)
2026-03-01 09:26:09,206 | INFO | [PROGRESS] Collecting scores | shards:2/18 (11.1%)
2026-03-01 09:26:10,152 | INFO | [PROGRESS] Collecting scores | shards:3/18 (16.7%)
2026-03-01 09:26:11,701 | INFO | [PROGRESS] Collecting scores | shards:4/18 (22.2%)
2026-03-01 09:26:13,270 | INFO | [PROGRESS] Collecting scores | shards:5/18 (27.8%)
2026-03-01 09:26:14,175 | INFO | [PROGRESS] Collecting scores | shards:6/18 (33.3%)
2026-03-01 09:26:15,721 | INFO | [PROGRESS] Collecting scores | shards:7/18 (38.9%)
2026-03-01 09:26:18,322 | INFO | [PROGRESS] Collecting scores | shards:8/18 (44.4%)
2026-03-01 09:26:19,144 | INFO | [PROGRESS] Collecting scores | shards:9/18 (50.0%)
2026-03-01 09:26:20,671 | INFO | [PROGRESS] Collecting scores | shards:10/18 (55.6%)
2026-03-01 09:26:22,292 | INFO | [PROGRESS] Collecting scores | shards:11/18 (61.1%)
2026-03-01 09:26:23,331 | INFO | [PROGRESS] Collecting scores | shards:12/18 (66.7%)
2026-03-01 09:26:24,854 | INFO | [PROGRESS] Collecting scores | shards:13/18 (72.2%)
2026-03-01 09:26:26,405 | INFO | [PROGRESS] Collecting scores | shards:14/18 (77.8%)
2026-03-01 09:26:27,220 | INFO | [PROGRESS] Collecting scores | shards:15/18 (83.3%)
2026-03-01 09:26:28,841 | INFO | [PROGRESS] Collecting scores | shards:16/18 (88.9%)
2026-03-01 09:26:30,408 | INFO | [PROGRESS] Collecting scores | shards:17/18 (94.4%)
2026-03-01 09:26:31,265 | INFO | [PROGRESS] Collecting scores | shards:18/18 (100.0%)
2026-03-01 09:26:32,314 | INFO | [PROGRESS] Collecting scores | shards:1/54 (1.9%)
2026-03-01 09:26:35,009 | INFO | [PROGRESS] Collecting scores | shards:4/54 (7.4%)
2026-03-01 09:26:37,666 | INFO | [PROGRESS] Collecting scores | shards:7/54 (13.0%)
2026-03-01 09:26:40,425 | INFO | [PROGRESS] Collecting scores | shards:10/54 (18.5%)
2026-03-01 09:26:44,387 | INFO | [PROGRESS] Collecting scores | shards:13/54 (24.1%)
2026-03-01 09:26:48,999 | INFO | [PROGRESS] Collecting scores | shards:16/54 (29.6%)
2026-03-01 09:26:53,080 | INFO | [PROGRESS] Collecting scores | shards:19/54 (35.2%)
2026-03-01 09:26:57,202 | INFO | [PROGRESS] Collecting scores | shards:22/54 (40.7%)
2026-03-01 09:27:02,207 | INFO | [PROGRESS] Collecting scores | shards:25/54 (46.3%)
2026-03-01 09:27:06,197 | INFO | [PROGRESS] Collecting scores | shards:28/54 (51.9%)
2026-03-01 09:27:10,128 | INFO | [PROGRESS] Collecting scores | shards:31/54 (57.4%)
2026-03-01 09:27:14,040 | INFO | [PROGRESS] Collecting scores | shards:34/54 (63.0%)
2026-03-01 09:27:17,330 | INFO | [PROGRESS] Collecting scores | shards:37/54 (68.5%)
2026-03-01 09:27:20,267 | INFO | [PROGRESS] Collecting scores | shards:40/54 (74.1%)
2026-03-01 09:27:23,636 | INFO | [PROGRESS] Collecting scores | shards:43/54 (79.6%)
2026-03-01 09:27:27,472 | INFO | [PROGRESS] Collecting scores | shards:46/54 (85.2%)
2026-03-01 09:27:31,563 | INFO | [PROGRESS] Collecting scores | shards:49/54 (90.7%)
2026-03-01 09:27:35,388 | INFO | [PROGRESS] Collecting scores | shards:52/54 (96.3%)
2026-03-01 09:27:37,789 | INFO | [PROGRESS] Collecting scores | shards:54/54 (100.0%)
2026-03-01 09:27:37,800 | INFO | [DONE] Threshold selected | method=target_percentile value=8.89005456 source_split=calib
2026-03-01 09:27:39,289 | INFO | [PROGRESS] CIC shards 1/18 (5.6%)
2026-03-01 09:27:40,852 | INFO | [PROGRESS] CIC shards 2/18 (11.1%)
2026-03-01 09:27:41,712 | INFO | [PROGRESS] CIC shards 3/18 (16.7%)
2026-03-01 09:27:43,330 | INFO | [PROGRESS] CIC shards 4/18 (22.2%)
2026-03-01 09:27:44,830 | INFO | [PROGRESS] CIC shards 5/18 (27.8%)
2026-03-01 09:27:45,682 | INFO | [PROGRESS] CIC shards 6/18 (33.3%)
2026-03-01 09:27:47,378 | INFO | [PROGRESS] CIC shards 7/18 (38.9%)
2026-03-01 09:27:48,981 | INFO | [PROGRESS] CIC shards 8/18 (44.4%)
2026-03-01 09:27:49,806 | INFO | [PROGRESS] CIC shards 9/18 (50.0%)
2026-03-01 09:27:51,759 | INFO | [PROGRESS] CIC shards 10/18 (55.6%)
2026-03-01 09:27:53,282 | INFO | [PROGRESS] CIC shards 11/18 (61.1%)
2026-03-01 09:27:54,087 | INFO | [PROGRESS] CIC shards 12/18 (66.7%)
2026-03-01 09:27:55,772 | INFO | [PROGRESS] CIC shards 13/18 (72.2%)
2026-03-01 09:27:57,374 | INFO | [PROGRESS] CIC shards 14/18 (77.8%)
2026-03-01 09:27:58,113 | INFO | [PROGRESS] CIC shards 15/18 (83.3%)
2026-03-01 09:27:59,678 | INFO | [PROGRESS] CIC shards 16/18 (88.9%)
2026-03-01 09:28:01,136 | INFO | [PROGRESS] CIC shards 17/18 (94.4%)
2026-03-01 09:28:02,039 | INFO | [PROGRESS] CIC shards 18/18 (100.0%)
2026-03-01 09:28:02,040 | INFO | [DONE] CIC eval complete | f1=0.7788 fpr=0.0108 roc_auc=None duration=24s
2026-03-01 09:28:02,372 | INFO | [PROGRESS] CSE shards 1/54 (1.9%)
2026-03-01 09:28:02,877 | INFO | [PROGRESS] CSE shards 3/54 (5.6%)
2026-03-01 09:28:03,495 | INFO | [PROGRESS] CSE shards 5/54 (9.3%)
2026-03-01 09:28:03,967 | INFO | [PROGRESS] CSE shards 7/54 (13.0%)
2026-03-01 09:28:04,445 | INFO | [PROGRESS] CSE shards 9/54 (16.7%)
2026-03-01 09:28:05,045 | INFO | [PROGRESS] CSE shards 11/54 (20.4%)
2026-03-01 09:28:05,555 | INFO | [PROGRESS] CSE shards 13/54 (24.1%)
2026-03-01 09:28:06,044 | INFO | [PROGRESS] CSE shards 15/54 (27.8%)
2026-03-01 09:28:06,648 | INFO | [PROGRESS] CSE shards 17/54 (31.5%)
2026-03-01 09:28:07,120 | INFO | [PROGRESS] CSE shards 19/54 (35.2%)
2026-03-01 09:28:07,605 | INFO | [PROGRESS] CSE shards 21/54 (38.9%)
2026-03-01 09:28:08,206 | INFO | [PROGRESS] CSE shards 23/54 (42.6%)
2026-03-01 09:28:08,713 | INFO | [PROGRESS] CSE shards 25/54 (46.3%)
2026-03-01 09:28:09,201 | INFO | [PROGRESS] CSE shards 27/54 (50.0%)
2026-03-01 09:28:09,829 | INFO | [PROGRESS] CSE shards 29/54 (53.7%)
2026-03-01 09:28:10,316 | INFO | [PROGRESS] CSE shards 31/54 (57.4%)
2026-03-01 09:28:10,806 | INFO | [PROGRESS] CSE shards 33/54 (61.1%)
2026-03-01 09:28:11,426 | INFO | [PROGRESS] CSE shards 35/54 (64.8%)
2026-03-01 09:28:11,925 | INFO | [PROGRESS] CSE shards 37/54 (68.5%)
2026-03-01 09:28:12,408 | INFO | [PROGRESS] CSE shards 39/54 (72.2%)
2026-03-01 09:28:13,018 | INFO | [PROGRESS] CSE shards 41/54 (75.9%)
2026-03-01 09:28:13,520 | INFO | [PROGRESS] CSE shards 43/54 (79.6%)
2026-03-01 09:28:14,008 | INFO | [PROGRESS] CSE shards 45/54 (83.3%)
2026-03-01 09:28:14,629 | INFO | [PROGRESS] CSE shards 47/54 (87.0%)
2026-03-01 09:28:15,141 | INFO | [PROGRESS] CSE shards 49/54 (90.7%)
2026-03-01 09:28:15,638 | INFO | [PROGRESS] CSE shards 51/54 (94.4%)
2026-03-01 09:28:16,262 | INFO | [PROGRESS] CSE shards 53/54 (98.1%)
2026-03-01 09:28:16,444 | INFO | [PROGRESS] CSE shards 54/54 (100.0%)
2026-03-01 09:28:16,444 | INFO | [DONE] CSE eval complete | f1=0.1633 fpr=0.0500 roc_auc=None duration=14s
/content/nids-cnn-lstm-autoencoder/scripts/eval_metrics.py:377: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()
2026-03-01 09:28:17,095 | INFO | [DONE] Evaluation finished | f1_gap=0.6155 auc_gap=0.0000 acc_gap=0.3769 duration=2m 20s
[RUN] s5_t02_target_p97 | stage=stage1 | stages=['eval'] | tag=s5_t02_target_p97
[CMD] /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t02_target_p97.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t02_target_p97
2026-03-01 09:28:21.264787: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772357301.287303   12325 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772357301.295176   12325 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772357301.312253   12325 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772357301.312287   12325 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772357301.312289   12325 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772357301.312291   12325 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[STAGE] Using GPU for evaluation (devices=1).
I0000 00:00:1772357305.879573   12325 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13655 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2026-03-01 09:28:26,934 | INFO | [STAGE] Evaluate shard mode | source_split=calib source_shards=18 cic_shards=18 cse_shards=54
I0000 00:00:1772357307.610481   12415 cuda_dnn.cc:529] Loaded cuDNN version 91002
2026-03-01 09:28:28,690 | INFO | [PROGRESS] Collecting scores | shards:1/18 (5.6%)
2026-03-01 09:28:29,052 | INFO | [PROGRESS] Collecting scores | shards:2/18 (11.1%)
2026-03-01 09:28:29,278 | INFO | [PROGRESS] Collecting scores | shards:3/18 (16.7%)
2026-03-01 09:28:29,596 | INFO | [PROGRESS] Collecting scores | shards:4/18 (22.2%)
2026-03-01 09:28:29,916 | INFO | [PROGRESS] Collecting scores | shards:5/18 (27.8%)
2026-03-01 09:28:30,129 | INFO | [PROGRESS] Collecting scores | shards:6/18 (33.3%)
2026-03-01 09:28:30,442 | INFO | [PROGRESS] Collecting scores | shards:7/18 (38.9%)
2026-03-01 09:28:30,750 | INFO | [PROGRESS] Collecting scores | shards:8/18 (44.4%)
2026-03-01 09:28:30,936 | INFO | [PROGRESS] Collecting scores | shards:9/18 (50.0%)
2026-03-01 09:28:31,233 | INFO | [PROGRESS] Collecting scores | shards:10/18 (55.6%)
2026-03-01 09:28:31,536 | INFO | [PROGRESS] Collecting scores | shards:11/18 (61.1%)
2026-03-01 09:28:31,719 | INFO | [PROGRESS] Collecting scores | shards:12/18 (66.7%)
2026-03-01 09:28:32,014 | INFO | [PROGRESS] Collecting scores | shards:13/18 (72.2%)
2026-03-01 09:28:32,316 | INFO | [PROGRESS] Collecting scores | shards:14/18 (77.8%)
2026-03-01 09:28:32,495 | INFO | [PROGRESS] Collecting scores | shards:15/18 (83.3%)
2026-03-01 09:28:32,787 | INFO | [PROGRESS] Collecting scores | shards:16/18 (88.9%)
2026-03-01 09:28:33,095 | INFO | [PROGRESS] Collecting scores | shards:17/18 (94.4%)
2026-03-01 09:28:33,282 | INFO | [PROGRESS] Collecting scores | shards:18/18 (100.0%)
2026-03-01 09:28:33,575 | INFO | [PROGRESS] Collecting scores | shards:1/54 (1.9%)
2026-03-01 09:28:34,347 | INFO | [PROGRESS] Collecting scores | shards:4/54 (7.4%)
2026-03-01 09:28:35,118 | INFO | [PROGRESS] Collecting scores | shards:7/54 (13.0%)
2026-03-01 09:28:35,883 | INFO | [PROGRESS] Collecting scores | shards:10/54 (18.5%)
2026-03-01 09:28:36,695 | INFO | [PROGRESS] Collecting scores | shards:13/54 (24.1%)
2026-03-01 09:28:37,471 | INFO | [PROGRESS] Collecting scores | shards:16/54 (29.6%)
2026-03-01 09:28:38,247 | INFO | [PROGRESS] Collecting scores | shards:19/54 (35.2%)
2026-03-01 09:28:39,064 | INFO | [PROGRESS] Collecting scores | shards:22/54 (40.7%)
2026-03-01 09:28:39,895 | INFO | [PROGRESS] Collecting scores | shards:25/54 (46.3%)
2026-03-01 09:28:40,733 | INFO | [PROGRESS] Collecting scores | shards:28/54 (51.9%)
2026-03-01 09:28:41,565 | INFO | [PROGRESS] Collecting scores | shards:31/54 (57.4%)
2026-03-01 09:28:42,357 | INFO | [PROGRESS] Collecting scores | shards:34/54 (63.0%)
2026-03-01 09:28:43,148 | INFO | [PROGRESS] Collecting scores | shards:37/54 (68.5%)
2026-03-01 09:28:43,942 | INFO | [PROGRESS] Collecting scores | shards:40/54 (74.1%)
2026-03-01 09:28:44,753 | INFO | [PROGRESS] Collecting scores | shards:43/54 (79.6%)
2026-03-01 09:28:45,539 | INFO | [PROGRESS] Collecting scores | shards:46/54 (85.2%)
2026-03-01 09:28:46,325 | INFO | [PROGRESS] Collecting scores | shards:49/54 (90.7%)
2026-03-01 09:28:47,100 | INFO | [PROGRESS] Collecting scores | shards:52/54 (96.3%)
2026-03-01 09:28:47,585 | INFO | [PROGRESS] Collecting scores | shards:54/54 (100.0%)
2026-03-01 09:28:47,591 | INFO | [DONE] Threshold selected | method=target_percentile value=10.72742950 source_split=calib
2026-03-01 09:28:47,890 | INFO | [PROGRESS] CIC shards 1/18 (5.6%)
2026-03-01 09:28:48,195 | INFO | [PROGRESS] CIC shards 2/18 (11.1%)
2026-03-01 09:28:48,379 | INFO | [PROGRESS] CIC shards 3/18 (16.7%)
2026-03-01 09:28:48,678 | INFO | [PROGRESS] CIC shards 4/18 (22.2%)
2026-03-01 09:28:48,992 | INFO | [PROGRESS] CIC shards 5/18 (27.8%)
2026-03-01 09:28:49,178 | INFO | [PROGRESS] CIC shards 6/18 (33.3%)
2026-03-01 09:28:49,480 | INFO | [PROGRESS] CIC shards 7/18 (38.9%)
2026-03-01 09:28:49,787 | INFO | [PROGRESS] CIC shards 8/18 (44.4%)
2026-03-01 09:28:49,974 | INFO | [PROGRESS] CIC shards 9/18 (50.0%)
2026-03-01 09:28:50,274 | INFO | [PROGRESS] CIC shards 10/18 (55.6%)
2026-03-01 09:28:50,581 | INFO | [PROGRESS] CIC shards 11/18 (61.1%)
2026-03-01 09:28:50,765 | INFO | [PROGRESS] CIC shards 12/18 (66.7%)
2026-03-01 09:28:51,072 | INFO | [PROGRESS] CIC shards 13/18 (72.2%)
2026-03-01 09:28:51,383 | INFO | [PROGRESS] CIC shards 14/18 (77.8%)
2026-03-01 09:28:51,568 | INFO | [PROGRESS] CIC shards 15/18 (83.3%)
2026-03-01 09:28:51,871 | INFO | [PROGRESS] CIC shards 16/18 (88.9%)
2026-03-01 09:28:52,210 | INFO | [PROGRESS] CIC shards 17/18 (94.4%)
2026-03-01 09:28:52,407 | INFO | [PROGRESS] CIC shards 18/18 (100.0%)
2026-03-01 09:28:52,407 | INFO | [DONE] CIC eval complete | f1=0.7723 fpr=0.0051 roc_auc=None duration=4s
2026-03-01 09:28:52,713 | INFO | [PROGRESS] CSE shards 1/54 (1.9%)
2026-03-01 09:28:53,203 | INFO | [PROGRESS] CSE shards 3/54 (5.6%)
2026-03-01 09:28:53,804 | INFO | [PROGRESS] CSE shards 5/54 (9.3%)
2026-03-01 09:28:54,277 | INFO | [PROGRESS] CSE shards 7/54 (13.0%)
2026-03-01 09:28:54,748 | INFO | [PROGRESS] CSE shards 9/54 (16.7%)
2026-03-01 09:28:55,340 | INFO | [PROGRESS] CSE shards 11/54 (20.4%)
2026-03-01 09:28:55,818 | INFO | [PROGRESS] CSE shards 13/54 (24.1%)
2026-03-01 09:28:56,308 | INFO | [PROGRESS] CSE shards 15/54 (27.8%)
2026-03-01 09:28:56,902 | INFO | [PROGRESS] CSE shards 17/54 (31.5%)
2026-03-01 09:28:57,386 | INFO | [PROGRESS] CSE shards 19/54 (35.2%)
2026-03-01 09:28:57,870 | INFO | [PROGRESS] CSE shards 21/54 (38.9%)
2026-03-01 09:28:58,490 | INFO | [PROGRESS] CSE shards 23/54 (42.6%)
2026-03-01 09:28:58,991 | INFO | [PROGRESS] CSE shards 25/54 (46.3%)
2026-03-01 09:28:59,496 | INFO | [PROGRESS] CSE shards 27/54 (50.0%)
2026-03-01 09:29:00,123 | INFO | [PROGRESS] CSE shards 29/54 (53.7%)
2026-03-01 09:29:00,618 | INFO | [PROGRESS] CSE shards 31/54 (57.4%)
2026-03-01 09:29:01,121 | INFO | [PROGRESS] CSE shards 33/54 (61.1%)
2026-03-01 09:29:01,744 | INFO | [PROGRESS] CSE shards 35/54 (64.8%)
2026-03-01 09:29:02,222 | INFO | [PROGRESS] CSE shards 37/54 (68.5%)
2026-03-01 09:29:02,702 | INFO | [PROGRESS] CSE shards 39/54 (72.2%)
2026-03-01 09:29:03,314 | INFO | [PROGRESS] CSE shards 41/54 (75.9%)
2026-03-01 09:29:03,817 | INFO | [PROGRESS] CSE shards 43/54 (79.6%)
2026-03-01 09:29:04,320 | INFO | [PROGRESS] CSE shards 45/54 (83.3%)
2026-03-01 09:29:04,937 | INFO | [PROGRESS] CSE shards 47/54 (87.0%)
2026-03-01 09:29:05,422 | INFO | [PROGRESS] CSE shards 49/54 (90.7%)
2026-03-01 09:29:05,940 | INFO | [PROGRESS] CSE shards 51/54 (94.4%)
2026-03-01 09:29:06,573 | INFO | [PROGRESS] CSE shards 53/54 (98.1%)
2026-03-01 09:29:06,764 | INFO | [PROGRESS] CSE shards 54/54 (100.0%)
2026-03-01 09:29:06,764 | INFO | [DONE] CSE eval complete | f1=0.0841 fpr=0.0300 roc_auc=None duration=14s
/content/nids-cnn-lstm-autoencoder/scripts/eval_metrics.py:377: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()
2026-03-01 09:29:07,361 | INFO | [DONE] Evaluation finished | f1_gap=0.6882 auc_gap=0.0000 acc_gap=0.3977 duration=41s
[RUN] s5_t03_target_p98 | stage=stage1 | stages=['eval'] | tag=s5_t03_target_p98
[CMD] /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t03_target_p98.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t03_target_p98
2026-03-01 09:29:10.910330: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772357350.932308   15520 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772357350.939875   15520 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772357350.957519   15520 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772357350.957550   15520 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772357350.957552   15520 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [10]:
# Cell 13: Execute stage2 (Sprint 5: no stage2, skip)
if RUN_STAGE2:
    run_stage('stage2')
else:
    print('[SKIP] stage2')

[SKIP] stage2

In [11]:
# Cell 14: Execute stage3 + stage4 (guardrail relax + seed candidates)
if RUN_STAGE3_4:
    run_cmd_stream(
        title='Sprint5 stage3+stage4',
        cmd='python scripts/sprint5/research_runner.py --stage-names stage3,stage4 --skip-existing',
    )
else:
    print('[SKIP] stage3,stage4')

[RUN] Sprint5 stage3+stage4
[CMD] /usr/bin/python3 scripts/sprint5/research_runner.py --stage-names stage3,stage4 --skip-existing
[RUN] s5_h01_guardrail_fpr012 | stage=stage3 | stages=['eval'] | tag=s5_h01_guardrail_fpr012
[CMD] /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_h01_guardrail_fpr012.yaml --model /content/sprint5_lock/s5_h01_guardrail_fpr012/best_model.keras --tag s5_h01_guardrail_fpr012
2026-03-01 09:51:48.583421: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772358708.606016   34972 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772358708.613958   34972 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772358708.631004   34972 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772358708.631034   34972 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772358708.631036   34972 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772358708.631038   34972 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[STAGE] Using GPU for evaluation (devices=1).
I0000 00:00:1772358713.075164   34972 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13655 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2026-03-01 09:51:54,046 | INFO | [STAGE] Evaluate shard mode | source_split=calib source_shards=18 cic_shards=18 cse_shards=54
I0000 00:00:1772358714.615852   35061 cuda_dnn.cc:529] Loaded cuDNN version 91002
2026-03-01 09:51:55,701 | INFO | [PROGRESS] Collecting scores | shards:1/18 (5.6%)
2026-03-01 09:51:56,037 | INFO | [PROGRESS] Collecting scores | shards:2/18 (11.1%)
2026-03-01 09:51:56,274 | INFO | [PROGRESS] Collecting scores | shards:3/18 (16.7%)
2026-03-01 09:51:56,609 | INFO | [PROGRESS] Collecting scores | shards:4/18 (22.2%)
2026-03-01 09:51:56,933 | INFO | [PROGRESS] Collecting scores | shards:5/18 (27.8%)
2026-03-01 09:51:57,159 | INFO | [PROGRESS] Collecting scores | shards:6/18 (33.3%)
2026-03-01 09:51:57,479 | INFO | [PROGRESS] Collecting scores | shards:7/18 (38.9%)
2026-03-01 09:51:57,787 | INFO | [PROGRESS] Collecting scores | shards:8/18 (44.4%)
2026-03-01 09:51:57,983 | INFO | [PROGRESS] Collecting scores | shards:9/18 (50.0%)
2026-03-01 09:51:58,301 | INFO | [PROGRESS] Collecting scores | shards:10/18 (55.6%)
2026-03-01 09:51:58,598 | INFO | [PROGRESS] Collecting scores | shards:11/18 (61.1%)
2026-03-01 09:51:58,773 | INFO | [PROGRESS] Collecting scores | shards:12/18 (66.7%)
2026-03-01 09:51:59,084 | INFO | [PROGRESS] Collecting scores | shards:13/18 (72.2%)
2026-03-01 09:51:59,380 | INFO | [PROGRESS] Collecting scores | shards:14/18 (77.8%)
2026-03-01 09:51:59,574 | INFO | [PROGRESS] Collecting scores | shards:15/18 (83.3%)
2026-03-01 09:51:59,891 | INFO | [PROGRESS] Collecting scores | shards:16/18 (88.9%)
2026-03-01 09:52:00,189 | INFO | [PROGRESS] Collecting scores | shards:17/18 (94.4%)
2026-03-01 09:52:00,385 | INFO | [PROGRESS] Collecting scores | shards:18/18 (100.0%)
2026-03-01 10:11:11,446 | INFO | [DONE] Threshold selected | method=source_calib_guardrail value=3.82237065 source_split=calib
2026-03-01 10:11:11,817 | INFO | [PROGRESS] CIC shards 1/18 (5.6%)
2026-03-01 10:11:12,185 | INFO | [PROGRESS] CIC shards 2/18 (11.1%)
2026-03-01 10:11:12,394 | INFO | [PROGRESS] CIC shards 3/18 (16.7%)
2026-03-01 10:11:12,757 | INFO | [PROGRESS] CIC shards 4/18 (22.2%)
2026-03-01 10:11:13,103 | INFO | [PROGRESS] CIC shards 5/18 (27.8%)
2026-03-01 10:11:13,296 | INFO | [PROGRESS] CIC shards 6/18 (33.3%)
2026-03-01 10:11:13,610 | INFO | [PROGRESS] CIC shards 7/18 (38.9%)
2026-03-01 10:11:13,924 | INFO | [PROGRESS] CIC shards 8/18 (44.4%)
2026-03-01 10:11:14,110 | INFO | [PROGRESS] CIC shards 9/18 (50.0%)
2026-03-01 10:11:14,418 | INFO | [PROGRESS] CIC shards 10/18 (55.6%)
2026-03-01 10:11:14,725 | INFO | [PROGRESS] CIC shards 11/18 (61.1%)
2026-03-01 10:11:14,929 | INFO | [PROGRESS] CIC shards 12/18 (66.7%)
2026-03-01 10:11:15,239 | INFO | [PROGRESS] CIC shards 13/18 (72.2%)
2026-03-01 10:11:15,543 | INFO | [PROGRESS] CIC shards 14/18 (77.8%)
2026-03-01 10:11:15,727 | INFO | [PROGRESS] CIC shards 15/18 (83.3%)
2026-03-01 10:11:16,040 | INFO | [PROGRESS] CIC shards 16/18 (88.9%)
2026-03-01 10:11:16,344 | INFO | [PROGRESS] CIC shards 17/18 (94.4%)
2026-03-01 10:11:16,532 | INFO | [PROGRESS] CIC shards 18/18 (100.0%)
2026-03-01 10:11:16,532 | INFO | [DONE] CIC eval complete | f1=0.8422 fpr=0.1207 roc_auc=None duration=5s
2026-03-01 10:11:16,831 | INFO | [PROGRESS] CSE shards 1/54 (1.9%)
2026-03-01 10:11:17,312 | INFO | [PROGRESS] CSE shards 3/54 (5.6%)
2026-03-01 10:11:17,906 | INFO | [PROGRESS] CSE shards 5/54 (9.3%)
2026-03-01 10:11:18,371 | INFO | [PROGRESS] CSE shards 7/54 (13.0%)
2026-03-01 10:11:18,834 | INFO | [PROGRESS] CSE shards 9/54 (16.7%)
2026-03-01 10:11:19,417 | INFO | [PROGRESS] CSE shards 11/54 (20.4%)
2026-03-01 10:11:19,911 | INFO | [PROGRESS] CSE shards 13/54 (24.1%)
2026-03-01 10:11:20,401 | INFO | [PROGRESS] CSE shards 15/54 (27.8%)
2026-03-01 10:11:21,010 | INFO | [PROGRESS] CSE shards 17/54 (31.5%)
2026-03-01 10:11:21,502 | INFO | [PROGRESS] CSE shards 19/54 (35.2%)
2026-03-01 10:11:21,995 | INFO | [PROGRESS] CSE shards 21/54 (38.9%)
2026-03-01 10:11:22,615 | INFO | [PROGRESS] CSE shards 23/54 (42.6%)
2026-03-01 10:11:23,160 | INFO | [PROGRESS] CSE shards 25/54 (46.3%)
2026-03-01 10:11:23,656 | INFO | [PROGRESS] CSE shards 27/54 (50.0%)
2026-03-01 10:11:24,274 | INFO | [PROGRESS] CSE shards 29/54 (53.7%)
2026-03-01 10:11:24,776 | INFO | [PROGRESS] CSE shards 31/54 (57.4%)
2026-03-01 10:11:25,273 | INFO | [PROGRESS] CSE shards 33/54 (61.1%)
2026-03-01 10:11:25,902 | INFO | [PROGRESS] CSE shards 35/54 (64.8%)
2026-03-01 10:11:26,411 | INFO | [PROGRESS] CSE shards 37/54 (68.5%)
2026-03-01 10:11:26,904 | INFO | [PROGRESS] CSE shards 39/54 (72.2%)
2026-03-01 10:11:27,510 | INFO | [PROGRESS] CSE shards 41/54 (75.9%)
2026-03-01 10:11:28,015 | INFO | [PROGRESS] CSE shards 43/54 (79.6%)
2026-03-01 10:11:28,519 | INFO | [PROGRESS] CSE shards 45/54 (83.3%)
2026-03-01 10:11:29,145 | INFO | [PROGRESS] CSE shards 47/54 (87.0%)
2026-03-01 10:11:29,660 | INFO | [PROGRESS] CSE shards 49/54 (90.7%)
2026-03-01 10:11:30,159 | INFO | [PROGRESS] CSE shards 51/54 (94.4%)
2026-03-01 10:11:30,797 | INFO | [PROGRESS] CSE shards 53/54 (98.1%)
2026-03-01 10:11:30,991 | INFO | [PROGRESS] CSE shards 54/54 (100.0%)
2026-03-01 10:11:30,992 | INFO | [DONE] CSE eval complete | f1=0.7442 fpr=0.2409 roc_auc=None duration=14s
/content/nids-cnn-lstm-autoencoder/scripts/eval_metrics.py:377: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()
2026-03-01 10:11:31,600 | INFO | [DONE] Evaluation finished | f1_gap=0.0980 auc_gap=0.0000 acc_gap=0.0973 duration=19m 38s
[RUN] s5_h02_guardrail_fpr015 | stage=stage3 | stages=['eval'] | tag=s5_h02_guardrail_fpr015
[CMD] /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_h02_guardrail_fpr015.yaml --model /content/sprint5_lock/s5_h02_guardrail_fpr015/best_model.keras --tag s5_h02_guardrail_fpr015
2026-03-01 10:11:39.390070: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772359899.412754   41809 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772359899.420531   41809 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772359899.438254   41809 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772359899.438286   41809 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772359899.438288   41809 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772359899.438290   41809 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[STAGE] Using GPU for evaluation (devices=1).
I0000 00:00:1772359904.151271   41809 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13655 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
2026-03-01 10:11:45,205 | INFO | [STAGE] Evaluate shard mode | source_split=calib source_shards=18 cic_shards=18 cse_shards=54
I0000 00:00:1772359905.902253   41899 cuda_dnn.cc:529] Loaded cuDNN version 91002
2026-03-01 10:11:46,964 | INFO | [PROGRESS] Collecting scores | shards:1/18 (5.6%)
2026-03-01 10:11:47,312 | INFO | [PROGRESS] Collecting scores | shards:2/18 (11.1%)
2026-03-01 10:11:47,552 | INFO | [PROGRESS] Collecting scores | shards:3/18 (16.7%)
2026-03-01 10:11:47,904 | INFO | [PROGRESS] Collecting scores | shards:4/18 (22.2%)
2026-03-01 10:11:48,249 | INFO | [PROGRESS] Collecting scores | shards:5/18 (27.8%)
2026-03-01 10:11:48,468 | INFO | [PROGRESS] Collecting scores | shards:6/18 (33.3%)
2026-03-01 10:11:48,787 | INFO | [PROGRESS] Collecting scores | shards:7/18 (38.9%)
2026-03-01 10:11:49,094 | INFO | [PROGRESS] Collecting scores | shards:8/18 (44.4%)
2026-03-01 10:11:49,276 | INFO | [PROGRESS] Collecting scores | shards:9/18 (50.0%)
2026-03-01 10:11:49,588 | INFO | [PROGRESS] Collecting scores | shards:10/18 (55.6%)
2026-03-01 10:11:49,900 | INFO | [PROGRESS] Collecting scores | shards:11/18 (61.1%)
2026-03-01 10:11:50,086 | INFO | [PROGRESS] Collecting scores | shards:12/18 (66.7%)
2026-03-01 10:11:50,399 | INFO | [PROGRESS] Collecting scores | shards:13/18 (72.2%)
2026-03-01 10:11:50,712 | INFO | [PROGRESS] Collecting scores | shards:14/18 (77.8%)
2026-03-01 10:11:50,896 | INFO | [PROGRESS] Collecting scores | shards:15/18 (83.3%)
2026-03-01 10:11:51,205 | INFO | [PROGRESS] Collecting scores | shards:16/18 (88.9%)
2026-03-01 10:11:51,509 | INFO | [PROGRESS] Collecting scores | shards:17/18 (94.4%)
2026-03-01 10:11:51,691 | INFO | [PROGRESS] Collecting scores | shards:18/18 (100.0%)
2026-03-01 10:30:56,361 | INFO | [DONE] Threshold selected | method=source_calib_guardrail value=3.49563622 source_split=calib
2026-03-01 10:30:56,724 | INFO | [PROGRESS] CIC shards 1/18 (5.6%)
2026-03-01 10:30:57,048 | INFO | [PROGRESS] CIC shards 2/18 (11.1%)
2026-03-01 10:30:57,232 | INFO | [PROGRESS] CIC shards 3/18 (16.7%)
2026-03-01 10:30:57,539 | INFO | [PROGRESS] CIC shards 4/18 (22.2%)
2026-03-01 10:30:57,846 | INFO | [PROGRESS] CIC shards 5/18 (27.8%)
2026-03-01 10:30:58,032 | INFO | [PROGRESS] CIC shards 6/18 (33.3%)
2026-03-01 10:30:58,333 | INFO | [PROGRESS] CIC shards 7/18 (38.9%)
2026-03-01 10:30:58,646 | INFO | [PROGRESS] CIC shards 8/18 (44.4%)
2026-03-01 10:30:58,832 | INFO | [PROGRESS] CIC shards 9/18 (50.0%)
2026-03-01 10:30:59,147 | INFO | [PROGRESS] CIC shards 10/18 (55.6%)
2026-03-01 10:30:59,455 | INFO | [PROGRESS] CIC shards 11/18 (61.1%)
2026-03-01 10:30:59,651 | INFO | [PROGRESS] CIC shards 12/18 (66.7%)
2026-03-01 10:30:59,952 | INFO | [PROGRESS] CIC shards 13/18 (72.2%)
2026-03-01 10:31:00,265 | INFO | [PROGRESS] CIC shards 14/18 (77.8%)
2026-03-01 10:31:00,452 | INFO | [PROGRESS] CIC shards 15/18 (83.3%)
2026-03-01 10:31:00,757 | INFO | [PROGRESS] CIC shards 16/18 (88.9%)
2026-03-01 10:31:01,061 | INFO | [PROGRESS] CIC shards 17/18 (94.4%)
2026-03-01 10:31:01,240 | INFO | [PROGRESS] CIC shards 18/18 (100.0%)
2026-03-01 10:31:01,240 | INFO | [DONE] CIC eval complete | f1=0.8474 fpr=0.1466 roc_auc=None duration=4s
2026-03-01 10:31:01,549 | INFO | [PROGRESS] CSE shards 1/54 (1.9%)
2026-03-01 10:31:02,031 | INFO | [PROGRESS] CSE shards 3/54 (5.6%)
2026-03-01 10:31:02,639 | INFO | [PROGRESS] CSE shards 5/54 (9.3%)
2026-03-01 10:31:03,120 | INFO | [PROGRESS] CSE shards 7/54 (13.0%)
2026-03-01 10:31:03,591 | INFO | [PROGRESS] CSE shards 9/54 (16.7%)
2026-03-01 10:31:04,188 | INFO | [PROGRESS] CSE shards 11/54 (20.4%)
2026-03-01 10:31:04,670 | INFO | [PROGRESS] CSE shards 13/54 (24.1%)
2026-03-01 10:31:05,158 | INFO | [PROGRESS] CSE shards 15/54 (27.8%)
2026-03-01 10:31:05,770 | INFO | [PROGRESS] CSE shards 17/54 (31.5%)
2026-03-01 10:31:06,265 | INFO | [PROGRESS] CSE shards 19/54 (35.2%)
2026-03-01 10:31:06,752 | INFO | [PROGRESS] CSE shards 21/54 (38.9%)
2026-03-01 10:31:07,375 | INFO | [PROGRESS] CSE shards 23/54 (42.6%)
2026-03-01 10:31:07,880 | INFO | [PROGRESS] CSE shards 25/54 (46.3%)
2026-03-01 10:31:08,381 | INFO | [PROGRESS] CSE shards 27/54 (50.0%)
2026-03-01 10:31:09,013 | INFO | [PROGRESS] CSE shards 29/54 (53.7%)
2026-03-01 10:31:09,515 | INFO | [PROGRESS] CSE shards 31/54 (57.4%)
2026-03-01 10:31:10,025 | INFO | [PROGRESS] CSE shards 33/54 (61.1%)
2026-03-01 10:31:10,644 | INFO | [PROGRESS] CSE shards 35/54 (64.8%)
2026-03-01 10:31:11,118 | INFO | [PROGRESS] CSE shards 37/54 (68.5%)
2026-03-01 10:31:11,604 | INFO | [PROGRESS] CSE shards 39/54 (72.2%)
2026-03-01 10:31:12,211 | INFO | [PROGRESS] CSE shards 41/54 (75.9%)
2026-03-01 10:31:12,721 | INFO | [PROGRESS] CSE shards 43/54 (79.6%)
2026-03-01 10:31:13,227 | INFO | [PROGRESS] CSE shards 45/54 (83.3%)
2026-03-01 10:31:13,838 | INFO | [PROGRESS] CSE shards 47/54 (87.0%)
2026-03-01 10:31:14,321 | INFO | [PROGRESS] CSE shards 49/54 (90.7%)
2026-03-01 10:31:14,812 | INFO | [PROGRESS] CSE shards 51/54 (94.4%)
2026-03-01 10:31:15,429 | INFO | [PROGRESS] CSE shards 53/54 (98.1%)
2026-03-01 10:31:15,626 | INFO | [PROGRESS] CSE shards 54/54 (100.0%)
2026-03-01 10:31:15,626 | INFO | [DONE] CSE eval complete | f1=0.7692 fpr=0.2681 roc_auc=None duration=14s
/content/nids-cnn-lstm-autoencoder/scripts/eval_metrics.py:377: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()
2026-03-01 10:31:16,208 | INFO | [DONE] Evaluation finished | f1_gap=0.0782 auc_gap=0.0000 acc_gap=0.0797 duration=19m 32s
[SKIP] s5_c01_seed42 gate_pass condition not met
[SKIP] s5_c02_seed1234 gate_pass condition not met
[DONE] summary: /content/nids-cnn-lstm-autoencoder/results/sprint5/summary.csv
[DONE] report: /content/nids-cnn-lstm-autoencoder/docs/sprint5/RESEARCH_REPORT_CSE_F1_SPRINT5.md
[DONE] gate: /content/nids-cnn-lstm-autoencoder/results/sprint5/gate_decision.json

[LOG] Full log saved to: /content/nids-cnn-lstm-autoencoder/results/sprint5/runtime/log_Sprint5_stage3+stage4_20260301_095143.txt

[EXIT CODE] 0
[DONE] Sprint5 stage3+stage4 in 39m 36s

In [12]:
# Cell 15: Execute summarize-only (aggregate hasil, gate decision, report)
if RUN_SUMMARIZE:
    run_cmd_stream(
        title='Sprint5 summarize-only',
        cmd='python scripts/sprint5/research_runner.py --summarize-only',
    )
else:
    print('[SKIP] summarize-only')

[RUN] Sprint5 summarize-only
[CMD] /usr/bin/python3 scripts/sprint5/research_runner.py --summarize-only
[DONE] summary: /content/nids-cnn-lstm-autoencoder/results/sprint5/summary.csv
[DONE] report: /content/nids-cnn-lstm-autoencoder/docs/sprint5/RESEARCH_REPORT_CSE_F1_SPRINT5.md
[DONE] gate: /content/nids-cnn-lstm-autoencoder/results/sprint5/gate_decision.json

[LOG] Full log saved to: /content/nids-cnn-lstm-autoencoder/results/sprint5/runtime/log_Sprint5_summarize-only_20260301_103120.txt

[EXIT CODE] 0
[DONE] Sprint5 summarize-only in 0s

## 3) Show Outputs (Summary, Gate, Report)

<!-- Cell 16: Header show outputs -->

In [13]:
# Cell 17: Tampilkan summary.csv, gate_decision.json, report markdown
import pandas as pd
from IPython.display import display, Markdown

summary_path = PROJECT_ROOT / 'results/sprint5/summary.csv'
gate_path = PROJECT_ROOT / 'results/sprint5/gate_decision.json'
report_path = PROJECT_ROOT / 'docs/sprint5/RESEARCH_REPORT_CSE_F1_SPRINT5.md'
status_path = PROJECT_ROOT / 'results/sprint5/runtime/run_status.json'

print('summary_path =', summary_path)
print('gate_path    =', gate_path)
print('report_path  =', report_path)
print('status_path  =', status_path)

if summary_path.exists():
    df = pd.read_csv(summary_path)
    print('\n[SUMMARY HEAD]')
    display(df.head(30))
    print('\n[STATUS COUNTS]')
    if 'terminal_status' in df.columns:
        display(df['terminal_status'].value_counts(dropna=False))
else:
    print('[WARN] summary.csv not found')

if gate_path.exists():
    gate = json.loads(gate_path.read_text(encoding='utf-8'))
    print('\n[GATE DECISION]')
    print(json.dumps(gate, indent=2))
else:
    print('[WARN] gate_decision.json not found')

if report_path.exists():
    print('\n[REPORT PREVIEW]')
    txt = report_path.read_text(encoding='utf-8')
    display(Markdown(txt[:8000]))
else:
    print('[WARN] report markdown not found')

if status_path.exists():
    print('\n[RUNTIME STATUS JSON]')
    print(status_path.read_text(encoding='utf-8')[:8000])

summary_path = /content/nids-cnn-lstm-autoencoder/results/sprint5/summary.csv
gate_path    = /content/nids-cnn-lstm-autoencoder/results/sprint5/gate_decision.json
report_path  = /content/nids-cnn-lstm-autoencoder/docs/sprint5/RESEARCH_REPORT_CSE_F1_SPRINT5.md
status_path  = /content/nids-cnn-lstm-autoencoder/results/sprint5/runtime/run_status.json

[SUMMARY HEAD]

,run_id,stage_name,profile,model_variant,active,condition,stages,tag,terminal_status,retry_count,...,cse_prec,cse_rec,cse_f1,cse_fpr,cse_auc,f1_gap,auc_gap,accuracy_gap,wall_time_sec,last_error
0,s5_00_lock_baseline,stage0,s5_hybrid_zero_shot_anomaly,hybrid,True,always,"preprocess,train,eval",s5_00_lock_baseline,success,0,...,0.874147,0.625923,0.729498,0.223683,NaN,0.102882,0.0,0.098824,2030.676788,NaN
1,s5_m07_rerun,stage0,s5_hybrid_zero_shot_anomaly,hybrid,True,always,"train,eval",s5_m07_rerun,success,0,...,0.885812,0.698368,0.781001,0.223459,NaN,0.046242,0.0,0.040696,1895.925668,NaN
2,s5_t01_target_p95,stage1,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_t01_target_p95,success,0,...,0.818296,0.090718,0.163330,0.050002,NaN,0.615469,0.0,0.376852,148.953151,NaN
3,s5_t02_target_p97,stage1,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_t02_target_p97,success,0,...,0.786038,0.044404,0.084059,0.030002,NaN,0.688204,0.0,0.397703,49.648651,NaN
4,s5_t03_target_p98,stage1,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_t03_target_p98,success,0,...,0.655400,0.015324,0.029949,0.020000,NaN,0.721921,0.0,0.394922,49.868047,NaN
5,s5_t04_target_p99,stage1,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_t04_target_p99,success,0,...,0.622131,0.006634,0.013128,0.010002,NaN,0.669943,0.0,0.332463,49.653070,NaN
6,s5_t05_target_p97_sub5pct,stage1,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_t05_target_p97_sub5pct,success,0,...,0.777619,0.039861,0.075835,0.028296,NaN,0.695194,0.0,0.399221,50.199284,NaN
7,s5_t06_target_p97_sub10pct,stage1,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_t06_target_p97_sub10pct,success,0,...,0.780241,0.041696,0.079162,0.029151,NaN,0.692467,0.0,0.398749,49.663279,NaN
8,s5_t07_source_calib_guardrail,stage1,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_t07_source_calib_guardrail,success,0,...,0.874147,0.625923,0.729498,0.223683,NaN,0.102882,0.0,0.098824,1155.430669,NaN
9,s5_h01_guardrail_fpr012,stage3,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_h01_guardrail_fpr012,success,0,...,0.870093,0.650106,0.744182,0.240929,NaN,0.098034,0.0,0.097272,1186.534233,NaN
10,s5_h02_guardrail_fpr015,stage3,s5_hybrid_zero_shot_anomaly,hybrid,True,always,eval,s5_h02_guardrail_fpr015,success,0,...,0.865079,0.692532,0.769248,0.268102,NaN,0.078199,0.0,0.079734,1180.423913,NaN
11,s5_c01_seed42,stage4,s5_hybrid_zero_shot_anomaly,hybrid,True,gate_pass,"preprocess,train,eval",s5_c01_seed42,skipped_gate,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,Gate not passed; stage4 skipped by design.
12,s5_c02_seed1234,stage4,s5_hybrid_zero_shot_anomaly,hybrid,True,gate_pass,"preprocess,train,eval",s5_c02_seed1234,skipped_gate,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,Gate not passed; stage4 skipped by design.

[STATUS COUNTS]

terminal_status
success         11
skipped_gate     2
Name: count, dtype: int64

[GATE DECISION]
{
  "generated_at": "2026-03-01T10:31:20.773978",
  "gate_pass": false,
  "reason": "failed_constraints",
  "adaptive_recall_target": 0.75,
  "adaptive_target_reasoning": "max(0.7500, baseline(0.0907)+0.0000)",
  "best_stage3_run_id": "s5_h02_guardrail_fpr015",
  "best_stage3_metrics": {
    "cse_recall": 0.692531678521269,
    "cse_precision": 0.8650786851154477,
    "cse_f1": 0.7692480839138802,
    "cic_fpr": 0.1465864080092318,
    "threshold": 3.495636224746704
  },
  "pivot_recommendation": "USAD",
  "stage_validity": {
    "stage1": {
      "required": 7,
      "valid_count": 7,
      "passed": true,
      "status": "ok"
    },
    "stage2": {
      "required": 0,
      "valid_count": 0,
      "passed": true,
      "status": "ok"
    },
    "stage3": {
      "required": 2,
      "valid_count": 2,
      "passed": true,
      "status": "ok"
    },
    "stage4": {
      "required": 2,
      "valid_count": 0,
      "passed": true,
      "status": "skipped_by_design"
    }
  },
  "sprint_history_summary": {
    "recall_p50": 0.04077874059075044,
    "recall_p90": 0.06756110069319417,
    "best_recall_under_guardrail": 0.09071849333539093,
    "best_recall_path": "/content/nids-cnn-lstm-autoencoder/results/sprint5/s5_t01_target_p95/metrics/s5_t01_target_p95_cse_metrics.json",
    "count_all": 11,
    "count_under_guardrail": 6
  }
}

[REPORT PREVIEW]

# RESEARCH REPORT CSE F1 - SPRINT 4

- generated_at: 2026-03-01T10:31:20.777780
- source_summary: `/content/nids-cnn-lstm-autoencoder/results/sprint5/summary.csv`
- gate_decision: `/content/nids-cnn-lstm-autoencoder/results/sprint5/gate_decision.json`

## Ringkasan / Summary

- Objective: maximize CSE recall dengan guardrail CIC FPR rendah.
- Objective (EN): maximize CSE recall under low CIC-FPR guardrail.
- Gate pass: `False` (reason: `failed_constraints`).
- Adaptive recall target: `0.75` (max(0.7500, baseline(0.0907)+0.0000)).

## Stage Validity

| stage | required_valid_runs | valid_runs | status |
| --- | ---: | ---: | --- |
| stage1 | 7 | 7 | ok |
| stage2 | 0 | 0 | ok |
| stage3 | 2 | 2 | ok |
| stage4 | 2 | 0 | skipped_by_design |

## Best Candidate Per Stage

| stage | run_id | mode | cse_recall | cse_precision | cse_f1 | cic_fpr |
| --- | --- | --- | ---: | ---: | ---: | ---: |
| stage0 | s5_m07_rerun | fallback | 0.6984 | 0.8858 | 0.7810 | 0.1087 |
| stage1 | s5_t01_target_p95 | hard | 0.0907 | 0.8183 | 0.1633 | 0.0108 |
| stage2 | - | - | - | - | - | - |
| stage3 | s5_h02_guardrail_fpr015 | worst_case | 0.6925 | 0.8651 | 0.7692 | 0.1466 |
| stage4 | - | - | - | - | - | - |

## Operational Notes

- ID Primary: Terminologi teknis tetap English untuk konsistensi.
- EN Mirror: Technical keywords are intentionally kept in English.

## Run Status

- total_runs: 13
- success: 11
- failed_experiment: 0
- failed_infra_exhausted: 0
- pending_or_skipped: 2

[RUNTIME STATUS JSON]
{
  "s5_00_lock_baseline": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 2030.6767876148224,
    "attempt_logs": []
  },
  "s5_m07_rerun": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 1895.9256675243378,
    "attempt_logs": []
  },
  "s5_t01_target_p95": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 148.9531512260437,
    "attempt_logs": [
      {
        "ts": "2026-03-01T07:22:39.140806",
        "kind": "experiment",
        "error": "Command failed rc=1 after 13.30s: /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t01_target_p95.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t01_target_p95"
      }
    ]
  },
  "s5_t02_target_p97": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 49.64865064620972,
    "attempt_logs": [
      {
        "ts": "2026-03-01T07:22:47.518191",
        "kind": "experiment",
        "error": "Command failed rc=1 after 8.30s: /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t02_target_p97.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t02_target_p97"
      }
    ]
  },
  "s5_t03_target_p98": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 49.86804676055908,
    "attempt_logs": [
      {
        "ts": "2026-03-01T07:22:55.955300",
        "kind": "experiment",
        "error": "Command failed rc=1 after 8.40s: /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t03_target_p98.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t03_target_p98"
      }
    ]
  },
  "s5_t04_target_p99": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 49.65306997299194,
    "attempt_logs": [
      {
        "ts": "2026-03-01T07:23:04.323623",
        "kind": "experiment",
        "error": "Command failed rc=1 after 8.34s: /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t04_target_p99.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t04_target_p99"
      }
    ]
  },
  "s5_t05_target_p97_sub5pct": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 50.199284076690674,
    "attempt_logs": [
      {
        "ts": "2026-03-01T07:23:12.719565",
        "kind": "experiment",
        "error": "Command failed rc=1 after 8.34s: /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t05_target_p97_sub5pct.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t05_target_p97_sub5pct"
      }
    ]
  },
  "s5_t06_target_p97_sub10pct": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 49.663278579711914,
    "attempt_logs": [
      {
        "ts": "2026-03-01T07:23:21.117735",
        "kind": "experiment",
        "error": "Command failed rc=1 after 8.36s: /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t06_target_p97_sub10pct.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t06_target_p97_sub10pct"
      }
    ]
  },
  "s5_t07_source_calib_guardrail": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 1155.4306690692902,
    "attempt_logs": [
      {
        "ts": "2026-03-01T07:23:29.513243",
        "kind": "experiment",
        "error": "Command failed rc=1 after 8.36s: /usr/bin/python3 scripts/sprint5/eval.py --config /content/nids-cnn-lstm-autoencoder/research/sprint5/generated_configs/s5_t07_source_calib_guardrail.yaml --model models/sprint5/s5_00_lock_baseline/cnn_lstm_ae/best_model.keras --tag s5_t07_source_calib_guardrail"
      }
    ]
  },
  "s5_h01_guardrail_fpr012": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 1186.5342330932617,
    "attempt_logs": []
  },
  "s5_h02_guardrail_fpr015": {
    "retry_count": 0,
    "terminal_status": "success",
    "last_error": "",
    "hash_violation": false,
    "wall_time_sec": 1180.423912525177,
    "attempt_logs": []
  },
  "s5_c01_seed42": {
    "retry_count": 0,
    "terminal_status": "skipped_gate",
    "last_error": "Gate not passed; stage4 skipped by design.",
    "hash_violation": false,
    "wall_time_sec": 0.0,
    "attempt_logs": []
  },
  "s5_c02_seed1234": {
    "retry_count": 0,
    "terminal_status": "skipped_gate",
    "last_error": "Gate not passed; stage4 skipped by design.",
    "hash_violation": false,
    "wall_time_sec": 0.0,
    "attempt_logs": []
  }
}

## 4) Resume Guide

<!-- Cell 18: Panduan resume setelah runtime putus -->

Kalau runtime Colab putus:
1. Run lagi dari cell mount + clone/pull + symlink.
2. Jalankan stage berikutnya atau stage yang sama.
3. `--skip-existing` akan melanjutkan dari artifact yang sudah ada.

## 5) Analisis Hasil Run — Sprint 5 Full Run History

> Bagian ini berisi temuan mendalam dari eksekusi Sprint 5 yang telah dijalankan di Colab (Tesla T4, TF 2.19.0).
> Diisi otomatis dari analisis output `histories-do-not-edit/sprint5-full-run.ipynb`.

---

### Ringkasan Status Run (13 total)

| Status | Jumlah | Keterangan |
|---|---|---|
| `success` | 2 | Stage 0 saja (lock_baseline + m07_rerun) |
| `failed_experiment` | 7 | Seluruh Stage 1 — FileNotFoundError |
| `skipped_inconclusive` | 2 | Stage 3 — bergantung stage1 yang gagal |
| `skipped_gate` | 2 | Stage 4 — gate_pass = False |

### Metrik Stage 0 yang Berhasil

| Run | CSE Recall | CSE F1 | CSE FPR | F1 Gap | Wall Time |
|---|---|---|---|---|---|
| `s5_00_lock_baseline` | 0.626 | 0.729 | 0.224 | 0.103 | ~33m 50s |
| `s5_m07_rerun` (mse_mae_mix α=0.7) | **0.698** | **0.781** | 0.224 | **0.046** | ~31m 36s |

**Temuan:** `mse_mae_mix` loss secara konsisten menghasilkan F1 lebih tinggi (+5.2pp) dan F1 gap jauh lebih kecil (0.046 vs 0.103), artinya generalisasi domain lebih baik.

### Gate Decision
```
gate_pass: false
reason: stage3_no_candidate
adaptive_recall_target: 0.75  (fixed_floor_only — no prior baseline)
pivot_recommendation: USAD
count_under_guardrail: 0  (CSE FPR ~0.224 >> guardrail 0.10)
```

### Root Cause — Bug Kritis Stage 1

**Error:**
```
FileNotFoundError: 'data/sprint5/s5_m07_rerun/processed/cic_val.npz'
```

**Rantai masalah:**
1. Semua 7 run Stage 1 memakai `reuse_data_from_best_stage: stage0`.
2. `select_best_run_id_for_stage('stage0')` memilih **`s5_m07_rerun`** (recall=0.698 > lock_baseline 0.626).
3. `apply_data_reuse_inputs(cfg, 's5_m07_rerun')` → set `shard_dir = data/sprint5/s5_m07_rerun/processed/shards`.
4. Tapi `s5_m07_rerun` sendiri punya `stages: [train, eval]` dan `reuse_data_from: s5_00_lock_baseline` — **tidak punya data di direktori isolated-nya sendiri**.
5. `eval_metrics.py` line 627 mencoba `np.load('data/sprint5/s5_m07_rerun/processed/cic_val.npz')` → FileNotFoundError.

**Cascade:**
- Stage 1: 0/7 valid → `inconclusive`.
- Stage 3 (`s5_h01`, `s5_h02`): `skipped_inconclusive` — butuh `template_from_best_stage=stage1`.
- Stage 4 (`s5_c01`, `s5_c02`): `skipped_gate` — gate_pass=False.

**Fix yang dibutuhkan di `scripts/sprint5/research_runner.py`:**
Fungsi `apply_data_reuse_inputs` (atau resolver `reuse_data_from_best_stage`) harus **mengikuti chain `reuse_data_from`** dari run yang dipilih sebagai best. Jika best-stage-run itu sendiri memakai reuse data dari run lain, gunakan sumber aslinya.

**Workaround sementara:** Ubah stage1 runs di `run_registry.yaml` dari `reuse_data_from_best_stage: stage0` menjadi `reuse_data_from: s5_00_lock_baseline` secara eksplisit (hard-code sumber data dari run yang punya preprocessing).

In [14]:
# Cell: Diagnosis helper — validasi apakah data dir stage0 runs tersedia
# Jalankan ini setelah stage0 selesai untuk memastikan stage1 tidak akan crash
import os
from pathlib import Path

ROOT = Path('/content/nids-cnn-lstm-autoencoder') if Path('/content/nids-cnn-lstm-autoencoder').exists() else Path('.')

stage0_runs = ['s5_00_lock_baseline', 's5_m07_rerun']
data_fields_to_check = ['cic_val.npz', 'cic_test.npz', 'cse_test.npz']

print('=== Stage 0 Data Directory Diagnosis ===')
for run_id in stage0_runs:
    data_dir = ROOT / 'data' / 'sprint5' / run_id / 'processed'
    print(f'\n[RUN] {run_id}')
    print(f'  data_dir: {data_dir}')
    print(f'  exists  : {data_dir.exists()}')
    if data_dir.exists():
        for fname in data_fields_to_check:
            fpath = data_dir / fname
            status = f'OK ({fpath.stat().st_size // 1024} KB)' if fpath.exists() else 'MISSING'
            print(f'  {fname}: {status}')
        # Also check shards
        shard_dir = data_dir / 'shards'
        print(f'  shards/: {"exists" if shard_dir.exists() else "MISSING"}')
        if shard_dir.exists():
            manifests = list(shard_dir.rglob('manifest.json'))
            print(f'  manifests found: {len(manifests)}')
            for m in manifests:
                print(f'    -> {m.relative_to(shard_dir)}')
    else:
        print('  [WARN] No preprocessed data in isolated dir — run uses reuse_data_from')

print()
print('=== Recommendation for Stage 1 ===')
lock_data = ROOT / 'data' / 'sprint5' / 's5_00_lock_baseline' / 'processed'
if lock_data.exists():
    print(f'[OK] Use reuse_data_from: s5_00_lock_baseline')
    print(f'     Path valid: {lock_data}')
else:
    print('[WARN] s5_00_lock_baseline data not found. Stage0 must run first.')

=== Stage 0 Data Directory Diagnosis ===

[RUN] s5_00_lock_baseline
  data_dir: /content/nids-cnn-lstm-autoencoder/data/sprint5/s5_00_lock_baseline/processed
  exists  : True
  cic_val.npz: MISSING
  cic_test.npz: MISSING
  cse_test.npz: MISSING
  shards/: exists
  manifests found: 5
    -> cic/train/manifest.json
    -> cic/val/manifest.json
    -> cic/calib/manifest.json
    -> cic/test/manifest.json
    -> cse/test/manifest.json

[RUN] s5_m07_rerun
  data_dir: /content/nids-cnn-lstm-autoencoder/data/sprint5/s5_m07_rerun/processed
  exists  : False
  [WARN] No preprocessed data in isolated dir — run uses reuse_data_from

=== Recommendation for Stage 1 ===
[OK] Use reuse_data_from: s5_00_lock_baseline
     Path valid: /content/nids-cnn-lstm-autoencoder/data/sprint5/s5_00_lock_baseline/processed

### Temuan Tambahan

#### 1. `sprint_history_summary.count_under_guardrail = 0`
Kedua run stage0 punya **CSE FPR ~0.224**, jauh di atas guardrail CIC FPR cap 0.10. Karena tidak ada run yang lolos guardrail, `best_recall_under_guardrail = null` dan `adaptive_recall_target` hanya bisa pakai `fixed_floor_only = 0.75` (tidak ada baseline yang bisa dijumlahkan). Ini artinya **threshold `source_calib_guardrail_fpr010` sangat agresif menekan CIC FPR tapi justru menaikkan CSE FPR**.

#### 2. Bugs di Notebook Ini (sudah teridentifikasi)
- `run_stage()` memakai prefix `'Sprint4 {stage_name}'` → seharusnya `'Sprint5 {stage_name}'`.
- Cell 17 `report_path` menunjuk ke `RESEARCH_REPORT_CSE_F1_SPRINT4.md` → seharusnya `SPRINT5.md`.
- Kedua bugs anotasi saja, tidak mempengaruhi eksekusi stage.

#### 3. Signal Positif — mse_mae_mix Loss (m07)
- Wall time lebih cepat (~2m lebih singkat dari lock_baseline).
- CSE recall +7.2pp, CSE F1 +5.2pp, F1 gap turun drastis (0.103 → 0.046).
- **Implikasi:** Jika stage1 bisa dijalankan (bug fixed), maka model m07 adalah kandidat kuat sebagai base untuk target-threshold experiments.

#### 4. Kondisi Gate Sprint 5
Untuk gate_pass=True dibutuhkan CSE recall ≥ 0.75 di stage3. Stage0 sudah menunjukkan recall 0.698 (m07) — **gap ke target hanya 0.052**. Jika `target_percentile` (p95–p99) bisa menurunkan threshold dan mendorong recall ≥ 0.75 tanpa collapse (precision ≥ 0.30), gate bisa tercapai.

---

### Action Items untuk Re-Run

| Prioritas | Item | File | Detail |
|---|---|---|---|
| 🔴 P0 | Fix `reuse_data_from_best_stage` chain resolution | `scripts/sprint5/research_runner.py` | Ikuti `reuse_data_from` dari run terpilih |
| 🟡 P1 | Workaround: hardcode stage1 → `reuse_data_from: s5_00_lock_baseline` | `research/sprint5/run_registry.yaml` | Semua 7 run stage1 |
| 🟢 P2 | Fix label notebook `Sprint4 →  Sprint5` | `notebooks/sprint5_colab_runner.ipynb` | Anotasi saja |
| 🟢 P2 | Fix `report_path` `SPRINT4.md → SPRINT5.md` | `notebooks/sprint5_colab_runner.ipynb` | Cell 17 |